remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Blue Drumlin
logo: /assets/img/Blue_Drumlin_Logo_500pxsq_whiteBG_Bold_D.png
author: Tygh Walters
description: Building on the web with Ruby on Rails
show_downloads: false
google_analytics:
# theme: jekyll-theme-minimal
